<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds the deterministic half of old-site URL continuity: the legacy entry
 * points whose replacement is a documented fact rather than an editorial call.
 *
 * Scope rules (see Docs/OLD_TO_NEW_REDIRECT_MIGRATION_COMPLETE.md):
 *
 *  - Only URLs whose new equivalent is proven are listed here. Old modules with
 *    no public equivalent on the new site (/alumni/, /downloads/, /members/,
 *    dent_conf_search.php) are deliberately absent so they keep returning a real
 *    404 and get logged into unresolved_legacy_requests for triage.
 *  - Nothing here points an unknown URL at the homepage.
 *  - Retired languages (old language ids 3/6/7 = German, Spanish, French) use the
 *    approved 302 fallback to /en, matching old_database.unsupported_language_continuity.
 *  - Every row carries a decision_batch so the whole set can be rolled back with
 *    legacy-import:redirect-rollback.
 *
 * These rows are stored WITHOUT a query_signature. For legacy router paths
 * (index.php) ContinuityService only matches a null signature when the incoming
 * request has no query string, so these rules resolve the bare subsite home URL
 * and can never hijack a deep content URL such as
 * /med/index.php?dir=items&page=show&cat_id=123 — those stay with the typed
 * query resolvers, or stay unresolved.
 */
class LegacyEntryPointRedirectSeeder extends Seeder
{
    private const BATCH = 'deterministic-entry-points-v1';

    /**
     * Old subsite router home => canonical new landing page.
     *
     * The old site served Arabic for a URL that carried no lang parameter, so a
     * bare router URL redirects straight to the Arabic page in one hop rather
     * than bouncing through locale negotiation.
     *
     * @var array<string, string>
     */
    private const SUBSITE_HOMES = [
        // The old site's own homepage.
        '/index.php' => '/ar',
        '/med/index.php' => '/ar/facilities/medicine',
        '/dent/index.php' => '/ar/facilities/dentistry',
        '/pharm/index.php' => '/ar/facilities/pharmacy',
        '/info/index.php' => '/ar/facilities/artificial-intelligence',
        '/petrol/index.php' => '/ar/facilities/petroleum',
        // The old public Business-faculty URL. It is NOT the new Laravel admin
        // panel; RedirectContinuityMiddleware whitelists this exact path so the
        // two never collide.
        '/admin/index.php' => '/ar/facilities/business-administration',
        '/research/index.php' => '/ar/research',
        '/hospital/index.php' => '/ar/campus-life/hospital',
        '/dent_clinic/index.php' => '/ar/campus-life/dental',
        '/clubs/index.php' => '/ar/campus-life/clubs-activities',
    ];

    /**
     * Old root entry points => new equivalent, with the status code to use.
     *
     * @var array<string, array{0: string, 1: int}>
     */
    private const ROOT_ENTRY_POINTS = [
        // Events listing pages (verified as real HTML pages on the old site).
        '/ar_events.php' => ['/ar/news/events-list', 301],
        '/en_events.php' => ['/en/news/events-list', 301],
        '/ar_cal_events.php' => ['/ar/news/events', 301],
        '/en_cal_events.php' => ['/en/news/events', 301],

        // Retired languages: approved 302 fallback, never a 301.
        '/ge_events.php' => ['/en', 302],
        '/sp_events.php' => ['/en', 302],
        '/fr_events.php' => ['/en', 302],
        '/ge_cal_events.php' => ['/en', 302],
        '/sp_cal_events.php' => ['/en', 302],
        '/fr_cal_events.php' => ['/en', 302],

        // The old sitemap was generated by PHP and is served as XML.
        '/sitemap.php' => ['/sitemap.xml', 301],
        '/sitemap1.php' => ['/sitemap.xml', 301],
        '/sitemap2.php' => ['/sitemap.xml', 301],

        // Homepage slider fragment: a visitor landing here wants the homepage.
        '/slider.php' => ['/ar', 301],
    ];

    public function run(): void
    {
        $now = now();
        $rows = [];

        foreach (self::ROOT_ENTRY_POINTS as $legacyPath => [$destination, $status]) {
            $rows[] = $this->row($legacyPath, $destination, $status, $now, 'Old root entry point.');
        }

        foreach (self::SUBSITE_HOMES as $legacyPath => $destination) {
            $rows[] = $this->row($legacyPath, $destination, 301, $now, 'Old subsite router home (bare URL, no query).');
        }

        foreach ($rows as $row) {
            DB::table('legacy_exact_redirects')->updateOrInsert(
                ['legacy_path' => $row['legacy_path'], 'query_signature' => null],
                $row,
            );
        }

        $this->command?->info(sprintf('Seeded %d deterministic legacy entry-point redirects.', count($rows)));
    }

    /**
     * @return array<string, mixed>
     */
    private function row(string $legacyPath, string $destination, int $status, \DateTimeInterface $now, string $note): array
    {
        return [
            'legacy_path' => $legacyPath,
            'query_signature' => null,
            'destination_url' => $destination,
            'status_code' => $status,
            'locale' => str_starts_with($destination, '/en') ? 'en' : 'ar',
            'is_active' => true,
            'notes' => $note.' Deterministic mapping, no editorial judgement required.',
            'decision_batch' => self::BATCH,
            'created_at' => $now,
            'updated_at' => $now,
        ];
    }
}
