@extends('layouts.public')

@include('public.research.partials.styles')

@section('content')
    @php($data = $page->data)
    @include('public.research.partials.page-hero', ['hero' => $data['hero'] ?? [], 'locale' => $locale, 'direction' => $direction])
    <section class="bg-white py-12 font-hacen md:py-16" dir="{{ $direction }}"><div class="container mx-auto px-6"><h1 class="sr-only">{{ $data['hero']['title'] ?? '' }}</h1><div class="mx-auto mb-10 max-w-[1200px]"><div class="flex flex-col gap-4 rounded-xl bg-spu-blue/[0.04] p-4 md:flex-row md:items-center"><div class="relative flex-1"><img src="/images/icon-search-outline.svg" alt="" class="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-spu-blue/40 rtl:left-auto rtl:right-4 rtl:rotate-180" aria-hidden="true"><input type="text" placeholder="{{ $data['searchPlaceholder'] ?? '' }}" class="h-12 w-full rounded-lg border border-spu-blue/10 bg-white py-3 pl-12 pr-4 text-sm text-spu-blue placeholder:text-spu-blue/40 focus:border-spu-blue focus:outline-none focus:ring-2 focus:ring-spu-blue/20 rtl:pl-4 rtl:pr-12 rtl:text-right"></div><div class="flex gap-3 md:w-auto"><select class="h-12 min-w-[160px] cursor-pointer rounded-lg border border-spu-blue/10 bg-white px-4 text-sm text-spu-blue focus:border-spu-blue focus:outline-none focus:ring-2 focus:ring-spu-blue/20"><option>{{ $data['filters']['allFaculties'] ?? '' }}</option>@foreach (($data['faculties'] ?? []) as $faculty)<option>{{ $faculty['name'] ?? '' }}</option>@endforeach</select><select class="h-12 min-w-[160px] cursor-pointer rounded-lg border border-spu-blue/10 bg-white px-4 text-sm text-spu-blue focus:border-spu-blue focus:outline-none focus:ring-2 focus:ring-spu-blue/20"><option>{{ $data['filters']['allExpertise'] ?? '' }}</option>@foreach (($data['expertiseAreas'] ?? []) as $area)<option>{{ $area['name'] ?? '' }}</option>@endforeach</select></div></div><p class="mt-4 text-sm text-spu-blue/60">{{ count($data['items'] ?? []) }} {{ $data['resultsLabel'] ?? '' }}</p></div><div class="mx-auto grid max-w-[1200px] gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">@foreach (($data['items'] ?? []) as $researcher)<a href="/{{ $locale }}/research/researchers/{{ $researcher['slug'] ?? '' }}" class="group flex flex-col items-center text-center"><div class="relative mb-4 h-28 w-28 overflow-hidden rounded-full border-2 border-spu-blue/10 transition-all group-hover:border-spu-red"><img src="{{ $researcher['image'] ?? '/images/uni-main-place.JPG' }}" alt="{{ $researcher['name'] ?? '' }}" class="h-full w-full object-cover object-top"></div><h3 class="mb-1 text-base font-bold text-spu-blue transition-colors group-hover:text-spu-red">{{ $researcher['name'] ?? '' }}</h3><p class="mb-2 text-sm text-spu-blue/70">{{ $researcher['faculty'] ?? '' }}</p><p class="text-xs font-semibold text-spu-blue/60">{{ $researcher['publications'] ?? 0 }} {{ $locale === 'ar' ? 'منشورات' : 'Publications' }}</p></a>@endforeach</div></div></section>
@endsection
