@extends('layouts.public')

@include('public.research.partials.styles')

@section('content')
    @php($data = $page->data)
    @include('public.research.partials.page-hero', ['hero' => $data['hero'] ?? [], 'locale' => $locale, 'direction' => $direction])
    <section class="bg-white py-12 font-hacen md:py-16" dir="{{ $direction }}"><div class="container mx-auto px-6"><div class="mx-auto mb-12 max-w-[1200px]"><h2 class="mb-2 text-center text-lg font-bold text-spu-red">{{ $data['resourcesSection']['title'] ?? '' }}</h2><p class="mb-8 text-center text-sm text-spu-blue/60">{{ $data['resourcesSection']['subtitle'] ?? '' }}</p><div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">@foreach (($data['databases'] ?? []) as $db)<a href="{{ $db['url'] ?? '#' }}" target="_blank" rel="noopener" class="group overflow-hidden rounded-xl border border-spu-blue/10 bg-white p-6 shadow-sm transition-all hover:border-spu-blue/30 hover:shadow-lg"><div class="mb-4 flex items-center justify-between"><h3 class="text-lg font-bold text-spu-blue transition-colors group-hover:text-spu-red">{{ $db['name'] ?? '' }}</h3><span class="inline-flex items-center rounded-full bg-spu-blue/5 px-2.5 py-1 text-[10px] font-semibold text-spu-blue/60">{{ $db['accessType'] ?? '' }}</span></div><p class="text-sm text-spu-blue/70">{{ $db['description'] ?? '' }}</p><div class="mt-4 flex items-center gap-1 text-xs font-semibold text-spu-red transition group-hover:text-spu-blue">{{ $locale === 'ar' ? 'افتح الآن' : 'Access Now' }}</div></a>@endforeach</div></div><div class="mx-auto mb-12 max-w-[1200px]"><h2 class="mb-8 text-center text-lg font-bold text-spu-blue">{{ $data['borrowingSection']['title'] ?? '' }}</h2><div class="grid gap-6 md:grid-cols-2">@foreach (($data['borrowingSection']['rules'] ?? []) as $rule)<div class="rounded-xl border border-spu-blue/10 bg-spu-blue/[0.02] p-6"><h3 class="mb-2 text-base font-bold text-spu-blue">{{ $rule['title'] ?? '' }}</h3><p class="text-sm text-spu-blue/70">{{ $rule['description'] ?? '' }}</p></div>@endforeach</div></div><div class="mx-auto mb-12 max-w-[1200px]"><h2 class="mb-8 text-center text-lg font-bold text-spu-blue">{{ $data['specialCollections']['title'] ?? '' }}</h2><div class="grid gap-6 md:grid-cols-2">@foreach (($data['specialCollections']['items'] ?? []) as $collection)<div class="rounded-xl border border-spu-blue/10 bg-white p-6 shadow-sm"><h3 class="mb-2 text-base font-bold text-spu-blue">{{ $collection['title'] ?? '' }}</h3><p class="text-sm text-spu-blue/70">{{ $collection['description'] ?? '' }}</p></div>@endforeach</div></div><div class="mx-auto max-w-[600px] rounded-xl border border-spu-blue/20 bg-spu-blue/[0.02] p-8 text-center"><h2 class="mb-4 text-lg font-bold text-spu-blue">{{ $data['librarianSection']['title'] ?? '' }}</h2><p class="text-sm font-bold text-spu-blue">{{ $data['librarianSection']['name'] ?? '' }}</p><p class="text-sm text-spu-blue/70">{{ $data['librarianSection']['hours'] ?? '' }}</p><div class="mt-4 flex flex-col gap-2 text-sm text-spu-blue/70"><a href="mailto:{{ $data['librarianSection']['email'] ?? '' }}" class="hover:text-spu-red">{{ $data['librarianSection']['email'] ?? '' }}</a><div>{{ $data['librarianSection']['phone'] ?? '' }}</div></div></div></div></section>
@endsection
