@extends('layouts.public')

@include('public.research.partials.styles')

@section('content')
    @php($item = $page->item)
    @php($data = $page->data)
    <section class="bg-white font-hacen" dir="{{ $direction }}"><div class="relative h-[50vh] min-h-[350px] overflow-hidden"><div class="absolute inset-0 bg-gradient-to-br from-spu-blue to-[#3a4280]"></div><div class="container relative z-10 flex h-full items-center justify-center"><div class="text-center"><p class="text-[12px] font-bold uppercase tracking-[0.16em] text-white/70">{{ $locale === 'ar' ? 'مجال بحثي' : 'Research Theme' }}</p><h1 class="mt-3 text-[32px] font-bold text-white md:text-[40px]">{{ $item['name'] ?? '' }}</h1><div class="mx-auto mt-6 flex items-center justify-center gap-8 text-[13px] text-white/80"><span><span class="font-bold text-white">{{ $item['publicationCount'] ?? 0 }}</span> {{ $locale === 'ar' ? 'منشور' : 'Publications' }}</span><span class="text-white/40">|</span><span><span class="font-bold text-white">{{ $item['projectCount'] ?? 0 }}</span> {{ $locale === 'ar' ? 'مشروع' : 'Projects' }}</span></div></div></div></div></section>
    <section class="bg-white pb-[80px] pt-[60px] font-hacen" dir="{{ $direction }}"><div class="container"><div class="mx-auto max-w-[1100px]"><div class="mb-12"><p class="text-[16px] leading-[1.8] text-[#50525c]">{{ $item['description'] ?? '' }}</p></div><div class="border-t border-[#e5e7eb] pt-10"><h2 class="text-[20px] font-bold text-spu-blue">{{ $locale === 'ar' ? 'المنشورات في هذا المجال' : 'Publications in this Theme' }}</h2><div class="mt-8 grid gap-[30px] lg:grid-cols-2">@foreach (($data['publications'] ?? []) as $publication)@include('public.research.partials.publication-card', ['publication' => $publication, 'locale' => $locale])@endforeach</div></div>@if (! empty($data['projects']))<div class="mt-12 border-t border-[#e5e7eb] pt-10"><h2 class="text-[20px] font-bold text-spu-blue">{{ $locale === 'ar' ? 'المشاريع في هذا المجال' : 'Projects in this Theme' }}</h2><div class="mt-8 grid gap-[30px] lg:grid-cols-2">@foreach ($data['projects'] as $project)@include('public.research.partials.project-card', ['project' => $project, 'locale' => $locale])@endforeach</div></div>@endif</div></div></section>
@endsection
