@extends('layouts.public')

@section('content')
    @php
        $section = $page->section;
        $type = $section['type'] ?? $page->sectionSlug;
        $hero = $section['hero'] ?? [];
        $breadcrumbs = $hero['breadcrumbs'] ?? [];
    @endphp

    @if (in_array($type, ['services', 'clubs-activities'], true))
        <section class="relative overflow-hidden font-hacen">
            <img src="{{ $hero['image'] ?? '/images/admissions-hero-campus.webp' }}" alt="{{ $hero['title'] ?? '' }}" class="h-[300px] w-full object-cover md:h-[340px]">
            <div class="absolute inset-0 bg-gradient-to-t from-spu-blue/80 via-spu-blue/50 to-spu-blue/0"></div>
            <div class="absolute inset-0"><div class="container flex h-full flex-col items-center justify-center text-center text-white">
                <nav class="flex flex-wrap items-center justify-center gap-2 text-xs font-semibold text-white/85">
                    @foreach ($breadcrumbs as $crumb)
                        <span class="inline-flex items-center gap-2"><a href="{{ $crumb['href'] ?? '#' }}" class="transition hover:text-white">{{ $crumb['label'] ?? '' }}</a>@if (! $loop->last)<img src="/images/icon-chevron-right-outline.svg" alt="" class="h-2.5 w-2.5 brightness-0 invert rtl:rotate-180" aria-hidden="true">@endif</span>
                    @endforeach
                </nav>
                <h1 class="mt-{{ $type === 'services' ? '2' : '3' }} {{ $type === 'services' ? 'text-4xl md:text-5xl' : 'text-3xl md:text-4xl' }} font-bold leading-tight">{{ $hero['title'] ?? '' }}</h1>
            </div></div>
        </section>

        @if ($type === 'services')
            <section class="bg-white py-14 font-hacen md:py-16">
                <div class="container">
                    <h2 class="text-center text-3xl font-bold text-spu-blue md:text-4xl">{{ $section['services']['title'] ?? '' }}</h2>
                    <div class="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-6">
                        @foreach (($section['services']['items'] ?? []) as $card)
                            <article class="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-[0_8px_20px_rgba(15,23,42,0.08)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_14px_30px_rgba(15,23,42,0.12)] {{ ($card['wide'] ?? false) ? 'lg:col-span-3' : 'lg:col-span-2' }}">
                                <img src="{{ $card['image'] ?? '' }}" alt="{{ $card['title'] ?? '' }}" class="h-40 w-full object-cover">
                                <div class="p-4"><h3 class="text-base font-bold text-spu-blue">{{ $card['title'] ?? '' }}</h3><div class="mt-3 rounded-md bg-[#f3f7fe] p-3 text-xs leading-5 text-slate-700"><p class="flex items-center gap-2 font-semibold text-spu-blue"><img src="/images/icon-file-outline.svg" alt="" class="h-3 w-3" aria-hidden="true"><span>{{ $section['services']['accessLabel'] ?? '' }}</span></p><p class="mt-1">{{ $card['access'] ?? '' }}</p></div><a href="{{ $card['href'] ?? '#' }}" class="mt-4 inline-flex items-center gap-2 text-xs font-bold text-spu-blue transition hover:text-spu-red"><span>{{ $section['services']['detailsLabel'] ?? '' }}</span><img src="/images/icon-arrow-right-outline.svg" alt="" class="h-2.5 w-2.5 rtl:rotate-180" aria-hidden="true"></a></div>
                            </article>
                        @endforeach
                    </div>
                </div>
            </section>
            <section class="bg-white pb-16 font-hacen md:pb-20"><div class="container"><article class="grid overflow-hidden rounded-lg bg-spu-blue text-white shadow-[0_16px_36px_rgba(15,23,42,0.16)] lg:grid-cols-2"><img src="{{ $section['support']['image'] ?? '' }}" alt="{{ $section['support']['imageAlt'] ?? '' }}" class="h-64 w-full object-cover lg:h-full"><div class="flex flex-col justify-center p-7 md:p-9"><h3 class="mt-3 text-3xl font-bold md:text-3xl">{{ $section['support']['title'] ?? '' }}</h3><p class="mt-4 text-xl leading-7 text-white/90">{{ $section['support']['summary'] ?? '' }}</p><div class="mt-6 grid gap-4 text-xs font-semibold sm:grid-cols-2">@foreach (($section['support']['badges'] ?? []) as $badge)<span class="inline-flex items-center gap-2"><img src="{{ $badge['icon'] ?? '' }}" alt="" class="h-4 w-4 brightness-0 invert" aria-hidden="true"><span>{{ $badge['label'] ?? '' }}</span></span>@endforeach</div></div></article></div></section>
        @else
            <section id="clubs" class="bg-white py-14 font-hacen md:py-16"><div class="container"><div class="flex items-end justify-between gap-6 border-b border-slate-200 pb-3"><h2 class="text-3xl font-bold text-spu-blue md:text-4xl">{{ $section['clubs']['title'] ?? '' }}</h2><a href="{{ $section['clubs']['directoryUrl'] ?? '#' }}" class="inline-flex shrink-0 items-center gap-2 text-xs font-bold text-spu-blue transition hover:text-spu-red"><span>{{ $section['clubs']['directoryLabel'] ?? '' }}</span><img src="/images/icon-chevron-right-outline.svg" alt="" class="h-3 w-3 rtl:rotate-180" aria-hidden="true"></a></div><div class="mt-8 grid gap-6 md:grid-cols-3">@foreach (($section['clubs']['items'] ?? []) as $club)<article class="group overflow-hidden rounded-lg border border-slate-200 bg-white shadow-[0_8px_20px_rgba(15,23,42,0.08)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_14px_30px_rgba(15,23,42,0.12)]"><div class="relative"><img src="{{ $club['image'] ?? '' }}" alt="{{ $club['title'] ?? '' }}" class="h-44 w-full object-cover transition duration-500 group-hover:scale-[1.03]"><span class="absolute left-3 top-3 rounded-sm bg-white px-2 py-1 text-[10px] font-bold text-spu-blue">{{ $club['tag'] ?? '' }}</span></div><div class="p-5"><h3 class="text-base font-bold text-spu-blue">{{ $club['title'] ?? '' }}</h3><p class="mt-3 min-h-[66px] text-xs leading-5 text-slate-600">{{ $club['summary'] ?? '' }}</p><a href="{{ $club['href'] ?? '#' }}" class="mt-4 inline-flex items-center gap-2 text-xs font-bold text-spu-blue transition hover:text-spu-red"><span>{{ $section['clubs']['detailsLabel'] ?? '' }}</span><img src="/images/icon-arrow-right-outline.svg" alt="" class="h-3 w-3 rtl:rotate-180" aria-hidden="true"></a></div></article>@endforeach</div></div></section>
            <section id="activities" class="bg-white pb-16 font-hacen md:pb-20"><div class="container"><div class="border-b border-slate-200 pb-3"><h2 class="text-3xl font-bold text-spu-blue md:text-4xl">{{ $section['activities']['title'] ?? '' }}</h2></div><div class="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_330px]"><article class="overflow-hidden"><a href="{{ $section['activities']['feature']['href'] ?? '#' }}" class="group block"><div class="relative overflow-hidden rounded-lg"><img src="{{ $section['activities']['feature']['image'] ?? '' }}" alt="{{ $section['activities']['feature']['title'] ?? '' }}" class="h-[360px] w-full object-cover transition duration-500 group-hover:scale-[1.03]"><span class="absolute left-4 top-4 rounded-sm bg-spu-red px-3 py-1.5 text-[10px] font-bold text-white">{{ $section['activities']['feature']['badge'] ?? '' }}</span></div><h3 class="mt-5 text-xl font-bold text-spu-blue">{{ $section['activities']['feature']['title'] ?? '' }}</h3><p class="mt-2 max-w-[780px] text-sm font-semibold leading-6 text-slate-700">{{ $section['activities']['feature']['summary'] ?? '' }}</p></a></article><aside class="flex flex-col gap-5">@foreach (($section['activities']['items'] ?? []) as $item)<a href="{{ $item['href'] ?? '#' }}" class="group grid grid-cols-[92px_minmax(0,1fr)] gap-4 border-b border-slate-200 pb-5 last:border-b-0"><img src="{{ $item['image'] ?? '' }}" alt="{{ $item['title'] ?? '' }}" class="h-20 w-full rounded-md object-cover"><span class="min-w-0"><span class="block text-[11px] font-bold text-spu-red">{{ $item['date'] ?? '' }}</span><span class="mt-1 block text-sm font-bold leading-5 text-spu-blue transition group-hover:text-spu-red">{{ $item['title'] ?? '' }}</span><span class="mt-1 block text-xs leading-5 text-slate-600">{{ $item['summary'] ?? '' }}</span></span></a>@endforeach<a href="{{ $section['activities']['announcementUrl'] ?? '#' }}" class="inline-flex items-center gap-2 pt-1 text-xs font-bold text-spu-red transition hover:text-spu-blue"><span>{{ $section['activities']['announcementLabel'] ?? '' }}</span><img src="/images/icon-arrow-right-outline.svg" alt="" class="h-3 w-3 rtl:rotate-180" aria-hidden="true"></a></aside></div></div></section>
        @endif
    @elseif ($type === 'transport')
        <section class="relative overflow-hidden font-hacen"><img src="{{ $hero['image'] ?? '/images/admissions-hero-campus.webp' }}" alt="{{ $hero['imageAlt'] ?? ($hero['title'] ?? '') }}" class="h-[320px] w-full object-cover md:h-[380px]"><div class="absolute inset-0 bg-gradient-to-t from-spu-blue/85 via-spu-blue/55 to-spu-blue/0"></div><div class="absolute inset-0"><div class="container flex h-full flex-col items-center justify-center text-center text-white"><nav class="flex flex-wrap items-center justify-center gap-2 text-xs font-semibold text-white/85">@foreach ($breadcrumbs as $crumb)<span class="inline-flex items-center gap-2"><a href="{{ $crumb['href'] ?? '#' }}" class="transition hover:text-white">{{ $crumb['label'] ?? '' }}</a>@if (! $loop->last)<img src="/images/icon-chevron-right-outline.svg" alt="" class="h-2.5 w-2.5 brightness-0 invert rtl:rotate-180" aria-hidden="true">@endif</span>@endforeach</nav><h1 class="mt-3 text-4xl font-bold leading-tight md:text-5xl">{{ $hero['title'] ?? '' }}</h1></div></div></section>
        <section class="bg-white py-16 font-hacen md:py-20"><div class="container"><h2 class="text-center text-3xl font-bold text-spu-blue md:text-4xl">{{ $section['overview']['title'] ?? '' }}</h2><div class="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">@foreach (($section['cards'] ?? []) as $card)<article class="rounded-lg border border-slate-200 bg-white p-6 shadow-[0_10px_24px_rgba(15,23,42,0.08)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_18px_34px_rgba(15,23,42,0.12)]"><div class="mb-5 flex h-12 w-12 items-center justify-center rounded-full bg-[#f3f6fb]"><img src="{{ $card['icon'] ?? '' }}" alt="" class="h-6 w-6" aria-hidden="true"></div><h3 class="text-lg font-bold text-spu-blue">{{ $card['title'] ?? '' }}</h3><p class="mt-3 text-sm leading-6 text-slate-600">{{ $card['description'] ?? '' }}</p><a href="{{ $card['href'] ?? '#' }}" class="mt-5 inline-flex items-center gap-2 text-xs font-bold text-spu-blue transition hover:text-spu-red"><span>{{ $card['cta'] ?? '' }}</span><img src="/images/icon-arrow-right-outline.svg" alt="" class="h-2.5 w-2.5 rtl:rotate-180" aria-hidden="true"></a></article>@endforeach</div></div></section>
        <section class="bg-white pb-16 font-hacen md:pb-20"><div class="container"><article class="grid overflow-hidden rounded-lg bg-spu-blue text-white shadow-[0_16px_36px_rgba(15,23,42,0.16)] lg:grid-cols-2"><img src="{{ $section['success']['image'] ?? '' }}" alt="{{ $section['success']['imageAlt'] ?? '' }}" class="h-64 w-full object-cover lg:h-full"><div class="flex flex-col justify-center p-7 md:p-9"><h2 class="text-2xl font-bold md:text-3xl">{{ $section['success']['title'] ?? '' }}</h2><p class="mt-4 text-sm leading-7 text-white/90">{{ $section['success']['description'] ?? '' }}</p><div class="mt-6 grid gap-4 text-xs font-semibold sm:grid-cols-2">@foreach (($section['success']['links'] ?? []) as $link)<span class="inline-flex items-center gap-2"><img src="{{ $link['icon'] ?? '' }}" alt="" class="h-4 w-4 brightness-0 invert" aria-hidden="true"><span>{{ $link['label'] ?? '' }}</span></span>@endforeach</div></div></article></div></section>
    @elseif ($type === 'career-development')
        <section class="relative bg-white font-hacen"><div class="relative h-[320px] overflow-hidden md:h-[360px]"><img src="{{ $hero['image'] ?? '' }}" alt="{{ $hero['title'] ?? '' }}" class="h-full w-full object-cover"><div class="absolute inset-0 bg-gradient-to-t from-spu-blue/80 via-spu-blue/50 to-spu-blue/0"></div><div class="absolute inset-0"><div class="container flex h-full flex-col items-center justify-center pt-16 text-center text-white"><nav class="flex flex-wrap items-center justify-center gap-2 text-[11px] font-semibold text-white/85">@foreach ($breadcrumbs as $crumb)<span class="inline-flex items-center gap-2"><a href="{{ $crumb['href'] ?? '#' }}" class="transition hover:text-white">{{ $crumb['label'] ?? '' }}</a>@if (! $loop->last)<img src="/images/icon-chevron-right-outline.svg" alt="" class="h-2.5 w-2.5 brightness-0 invert rtl:rotate-180" aria-hidden="true">@endif</span>@endforeach</nav><h1 class="mt-2 text-4xl font-bold leading-tight md:text-5xl">{{ $hero['title'] ?? '' }}</h1></div></div></div><div class="container relative z-10 -mt-16"><article class="mx-auto max-w-[760px] bg-spu-blue px-8 py-8 text-center text-white shadow-[0_16px_32px_rgba(15,23,42,0.18)] md:px-12"><h2 class="text-2xl font-bold">{{ $hero['panel']['title'] ?? '' }}</h2><p class="mx-auto mt-3 max-w-[620px] text-sm leading-6 text-white/88">{{ $hero['panel']['summary'] ?? '' }}</p></article></div></section>
        <section class="bg-white py-16 font-hacen md:py-20"><div class="container"><h2 class="text-center text-3xl font-bold text-spu-blue md:text-4xl">{{ $section['services']['title'] ?? '' }}</h2><div class="mt-10 grid gap-7 md:grid-cols-2 lg:grid-cols-3">@foreach (($section['services']['items'] ?? []) as $card)<article id="{{ $card['id'] ?? '' }}" class="min-h-[174px] rounded-md border border-slate-200 bg-white p-6 shadow-[0_10px_24px_rgba(15,23,42,0.08)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_18px_34px_rgba(15,23,42,0.12)]"><div class="flex items-start justify-between gap-4"><h3 class="text-base font-bold text-spu-blue">{{ $card['title'] ?? '' }}</h3><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#f3f6fb]"><img src="{{ $card['icon'] ?? '' }}" alt="" class="h-4 w-4 opacity-85" aria-hidden="true"></span></div><p class="mt-3 text-xs leading-5 text-slate-600">{{ $card['summary'] ?? '' }}</p><a href="{{ $card['href'] ?? '#' }}" class="mt-5 inline-flex items-center gap-2 text-xs font-bold text-spu-blue transition hover:text-spu-red"><span>{{ $card['link'] ?? '' }}</span><img src="/images/icon-arrow-right-outline.svg" alt="" class="h-2.5 w-2.5 rtl:rotate-180" aria-hidden="true"></a></article>@endforeach</div></div></section>
        <section class="bg-white pb-16 font-hacen md:pb-20"><div class="container"><article class="grid overflow-hidden rounded-md bg-spu-blue text-white shadow-[0_16px_36px_rgba(15,23,42,0.16)] lg:grid-cols-[1fr_1.12fr]"><img src="{{ $section['success']['image'] ?? '' }}" alt="{{ $section['success']['imageAlt'] ?? '' }}" class="h-64 w-full object-cover lg:h-full"><div class="flex min-h-[260px] flex-col justify-center p-7 md:p-9"><h2 class="text-2xl font-bold md:text-3xl">{{ $section['success']['title'] ?? '' }}</h2><p class="mt-4 max-w-[620px] text-sm leading-7 text-white/90">{{ $section['success']['summary'] ?? '' }}</p><div class="mt-6 grid gap-4 text-xs font-semibold sm:grid-cols-2">@foreach (($section['success']['badges'] ?? []) as $badge)<span class="inline-flex items-center gap-2"><img src="{{ $badge['icon'] ?? '' }}" alt="" class="h-4 w-4 brightness-0 invert" aria-hidden="true"><span>{{ $badge['label'] ?? '' }}</span></span>@endforeach</div></div></article></div></section>
    @elseif (in_array($type, ['dental', 'hospital'], true))
        <section class="relative mx-auto flex min-h-[65vh] items-center justify-center overflow-hidden font-hacen md:min-h-[75vh] lg:min-h-[85vh]"><div class="absolute inset-0 z-0"><img src="{{ $hero['image'] ?? '' }}" class="h-full w-full scale-[1.05] object-cover transition-transform duration-[10000ms] hover:scale-100" alt="{{ $hero['title'] ?? '' }}"><div class="absolute inset-0 bg-gradient-to-t from-spu-blue/90 via-spu-blue/60 to-spu-blue/0"></div></div><div class="container relative z-10 mx-auto pb-12 pt-40 text-center"><div class="mx-auto w-[70%] text-center" data-reveal="left"><nav class="mb-6 flex flex-wrap items-center justify-center gap-2 text-sm font-medium text-white/70 md:text-base">@foreach ($breadcrumbs as $crumb)<a href="{{ $crumb['href'] ?? '#' }}" class="transition-colors hover:text-white {{ $loop->last ? 'font-semibold text-white' : '' }}">{{ $crumb['label'] ?? '' }}</a>@if (! $loop->last)<img src="/images/icon-chevron-right-outline.svg" alt="" class="h-2.5 w-2.5 rtl:rotate-180" aria-hidden="true">@endif @endforeach</nav><h1 class="mb-6 text-4xl font-bold leading-[1.05] tracking-tight text-white sm:text-2xl md:text-[50px]">{{ $hero['title'] ?? '' }}</h1><p class="mx-auto mb-10 text-base leading-relaxed text-white/90 sm:text-lg md:text-[20px]">{{ $hero['summary'] ?? '' }}</p><a href="{{ $hero['ctaUrl'] ?? '#' }}" target="_blank" rel="noreferrer noopener" class="inline-flex items-center justify-center gap-3 rounded-full bg-spu-red px-10 py-4 font-semibold text-white shadow-2xl shadow-spu-red/20 transition-all duration-300 hover:bg-white hover:text-spu-blue"><span>{{ $hero['cta'] ?? '' }}</span><img src="/images/icon-map-outline.svg" alt="" class="h-5 w-5 brightness-0 invert" aria-hidden="true"></a></div></div></section>
        <section class="bg-white py-24 font-hacen"><div class="container"><div class="mb-16 text-center"><h2 class="text-5xl font-bold text-spu-blue">{{ $section['sectionHeader']['title'] ?? '' }}</h2></div>
            @if ($type === 'dental')<div class="grid grid-cols-1 gap-6 md:grid-cols-3">@foreach (($section['services'] ?? []) as $service)<div class="flex h-full flex-col rounded-[12px] border border-[#C3C6D180] bg-white p-10 transition-all duration-300 hover:border-slate-200 hover:shadow-xl {{ $loop->first || $loop->last ? 'md:col-span-2' : 'md:col-span-1' }}"><div class="mb-6 flex items-start justify-between"><h3 class="text-2xl font-bold text-[#1e2d5b]">{{ $service['title'] ?? '' }}</h3><div class="flex items-center justify-center"><img src="{{ $service['icon'] ?? '' }}" class="h-12 w-12 object-contain transition-transform duration-300 group-hover:scale-110" alt=""></div></div><p class="max-w-2xl text-lg leading-relaxed text-slate-500">{{ $service['description'] ?? '' }}</p></div>@endforeach</div>
            @else<div class="grid grid-cols-1 gap-6 md:grid-cols-2">@foreach (($section['departments'] ?? []) as $dept)<div class="group flex h-full flex-col rounded-[8px] border border-[#C3C6D180] bg-white p-10 transition-all duration-300 hover:border-slate-200 hover:shadow-xl"><div class="mb-6 flex items-start justify-between"><h3 class="text-2xl font-bold text-[#1e2d5b]">{{ $dept['title'] ?? '' }}</h3><div class="flex items-center justify-center"><img src="{{ $dept['icon'] ?? '' }}" class="h-12 w-12 bg-white text-black" alt=""></div></div><p class="text-lg leading-relaxed text-slate-500">{{ $dept['description'] ?? '' }}</p></div>@endforeach</div>@endif
        </div><div id="weekly-schedule" class="container mt-24 pb-20"><div class="mb-16 text-center"><h2 class="text-5xl font-bold text-[#1e2d5b]">{{ $section['scheduleSection']['title'] ?? '' }}</h2></div><div class="grid items-stretch gap-{{ $type === 'dental' ? '[94px]' : '10' }} lg:grid-cols-2"><div class="flex flex-col items-center justify-center rounded-[8px] bg-[#1e2d5b] p-{{ $type === 'dental' ? '10' : '12' }} text-center text-white shadow-xl"><div class="mb-6"><img src="/images/time.svg" alt="" class="h-[97px] w-[97px] brightness-0 invert" aria-hidden="true"></div><div class="mb-8 inline-block rounded-full px-6 py-1.5 text-sm font-bold shadow-sm transition-colors duration-300 {{ ($section['today']['isEmergency'] ?? false) ? 'bg-red-600 text-white' : 'bg-white text-[#1e2d5b]' }}"><span>{{ ($section['today']['isEmergency'] ?? false) ? ($section['scheduleSection']['statusClosed'] ?? '') : ($section['scheduleSection']['status'] ?? '') }}</span></div><h3 class="mb-1 text-3xl font-bold"><span>{{ $locale === 'ar' ? 'اليوم: ' : 'Today: ' }}</span><span>{{ $section['today']['time'] ?? '' }}</span></h3><p class="mb-4 text-sm font-medium text-white/60">{{ now()->locale($locale)->translatedFormat('l, F j, Y') }}</p><p class="max-w-sm text-lg text-slate-300">{{ $section['scheduleDetails'] ?? '' }}</p></div><div class="rounded-[8px] border border-[#C3C6D180] bg-white p-10 shadow-sm"><div class="space-y-6">@foreach (($section['schedule'] ?? []) as $slot)<div class="flex items-center justify-between border-b border-slate-100 pb-4 last:border-0 last:pb-0"><span class="font-medium {{ ($slot['isEmergency'] ?? false) ? 'text-red-500' : 'text-slate-500' }}">{{ $slot['day'] ?? '' }}</span><span class="font-semibold {{ ($slot['isEmergency'] ?? false) ? 'text-red-500' : 'text-[#1e2d5b]' }}">{{ $slot['time'] ?? '' }}</span></div>@endforeach</div></div></div></div>
        @if ($type === 'hospital')<div class="container"><div class="flex flex-col items-center justify-between gap-8 rounded-[8px] p-8 shadow-[0px_4px_12px_0px_rgba(51,51,51,0.08)] md:flex-row"><div class="flex items-center gap-5"><div class="flex h-12 w-12 items-center justify-center rounded-xl bg-white shadow-sm"><img src="{{ $section['emergency']['icon'] ?? '' }}" class="h-full w-full object-cover" alt=""></div><div><h4 class="text-lg font-bold text-[#1e2d5b]">{{ $section['emergency']['label'] ?? '' }}</h4><p class="text-sm font-bold tracking-wider text-[#737780]">{{ $section['emergency']['status'] ?? '' }}</p></div></div><div class="hidden border-x border-[#E2E8F0] px-12 text-center md:text-left lg:block"><p class="mb-1 text-sm font-medium text-slate-500">{{ $section['emergency']['hotlineLabel'] ?? '' }}</p><p class="text-xl font-bold text-[#1e2d5b]">{{ $section['emergency']['phone'] ?? '' }}</p></div><div class="flex flex-wrap items-center justify-center gap-4"><a href="tel:{{ $section['emergency']['phone'] ?? '' }}" class="inline-flex items-center gap-3 rounded-xl bg-spu-red px-8 py-3 font-bold text-white shadow-lg shadow-red-900/10 transition-colors hover:bg-[#4a1212]"><img src="/images/icon-phone-outline.svg" alt="" class="h-4 w-4" aria-hidden="true"><span>{{ $section['emergency']['callCta'] ?? '' }}</span></a><a href="{{ $hero['ctaUrl'] ?? '#' }}" target="_blank" class="inline-flex items-center gap-3 rounded-xl border border-[#CBD5E1] bg-white px-8 py-3 font-bold text-[#1e2d5b] transition-colors hover:bg-[#F1F5F9]"><img src="/images/icon-map-outline.svg" alt="" class="h-4 w-4 opacity-60" aria-hidden="true"><span>{{ $section['emergency']['directionsCta'] ?? '' }}</span></a></div></div></div>@endif
        </section>
    @elseif ($type === 'health-insurance')
        <section class="relative mx-auto flex min-h-[58vh] items-center justify-center overflow-hidden font-hacen md:min-h-[68vh]"><div class="absolute inset-0 z-0"><img src="{{ $hero['image'] ?? '' }}" class="h-full w-full object-cover" alt="{{ $hero['title'] ?? '' }}"><div class="absolute inset-0 bg-gradient-to-t from-spu-blue/90 via-spu-blue/60 to-spu-blue/0"></div></div><div class="container relative z-10 mx-auto pb-12 pt-40 text-center"><nav class="mb-6 flex flex-wrap items-center justify-center gap-2 text-sm font-medium text-white/75 md:text-base">@foreach ($breadcrumbs as $crumb)<a href="{{ $crumb['href'] ?? '#' }}" class="hover:text-white {{ $loop->last ? 'font-semibold text-white' : '' }}">{{ $crumb['label'] ?? '' }}</a>@if (! $loop->last)<img src="/images/icon-chevron-right-outline.svg" alt="" class="h-2.5 w-2.5 rtl:rotate-180" aria-hidden="true">@endif @endforeach</nav><h1 class="mb-6 text-4xl font-bold text-white md:text-[54px]">{{ $hero['title'] ?? '' }}</h1></div></section>
        <section class="relative bg-white py-16 font-hacen md:py-24"><div class="container">@foreach (($section['sections'] ?? []) as $content)
            @if (($content['type'] ?? '') === 'highlight')<div class="absolute left-[50%] z-20 translate-x-[-50%] rounded-[4px] border border-[#E4E1E6] bg-spu-blue px-12 py-8 text-center text-white shadow-xl md:top-[-80px] md:px-28 md:py-10"><h2 class="mb-3 text-[34px] font-bold md:text-[40px]">{{ $content['title'] ?? '' }}</h2><p class="mx-auto max-w-4xl text-sm leading-relaxed text-white/90 md:text-[15px]">{{ $content['description'] ?? '' }}</p></div>@endif
            @if (($content['type'] ?? '') === 'steps')<div class="mt-24 md:mt-28"><h3 class="mb-10 text-center text-[38px] font-bold text-spu-blue md:mb-12 md:text-[48px]">{{ $content['title'] ?? '' }}</h3><div class="grid gap-x-10 gap-y-8 md:grid-cols-2">@foreach (($content['items'] ?? []) as $item)<div><p class="text-[42px] font-bold leading-none text-[#D0D6E6] md:text-[50px]">{{ $item['number'] ?? '' }}</p><h4 class="mb-2 text-[28px] font-bold text-spu-blue">{{ $item['title'] ?? '' }}</h4><p class="leading-relaxed text-[#5B6277]">{{ $item['desc'] ?? '' }}</p></div>@endforeach</div></div>@endif
            @if (($content['type'] ?? '') === 'cards')<div class="mt-20 md:mt-24"><h3 class="mb-8 text-center text-[38px] font-bold text-spu-blue md:mb-10 md:text-[48px]">{{ $content['title'] ?? '' }}</h3><div class="grid gap-4 md:grid-cols-2 md:gap-5 lg:grid-cols-4">@foreach (($content['items'] ?? []) as $item)<div class="rounded-[8px] border border-[#DCE1ED] bg-white p-5 shadow-[0px_4px_12px_0px_rgba(51,51,51,0.06)]"><div class="mb-4 flex items-center justify-between gap-3"><h4 class="mb-2 text-[19px] font-bold text-spu-blue">{{ $item['title'] ?? '' }}</h4><img src="{{ $item['icon'] ?? '' }}" class="h-6 w-6 object-contain" aria-hidden="true" alt=""></div><p class="text-sm leading-relaxed text-[#5B6277]">{{ $item['desc'] ?? '' }}</p></div>@endforeach</div></div>@endif
            @if (($content['type'] ?? '') === 'documents')<div class="mt-20 md:mt-24"><h3 class="mb-10 text-[38px] font-bold text-spu-blue md:text-[44px] {{ $locale === 'ar' ? 'text-right' : 'text-left' }}">{{ $content['title'] ?? '' }}</h3><div class="grid items-stretch gap-8 lg:grid-cols-[1.8fr_1fr]"><div class="rounded-[8px] border border-[#C3C6D14D] px-6 py-12 shadow-[4px_0_12px_0_rgba(51,51,51,0.08)]"><ul class="space-y-3 text-[#3C435D]">@foreach (($content['list'] ?? []) as $item)<li class="flex items-start gap-3"><img src="/images/icon-check-circle-outline.svg" class="mt-1 h-5 w-5 shrink-0" aria-hidden="true" alt=""><span>{{ $item }}</span></li>@endforeach</ul></div><aside class="flex flex-col justify-between rounded-[12px] bg-spu-blue px-6 py-7 text-white shadow-lg"><h4 class="mb-4 border-b border-[#A7C8FF4D] pb-1 text-[26px] font-bold">{{ $content['support']['title'] ?? '' }}</h4><p class="mb-3 flex items-center gap-3 text-white/90"><img src="{{ $content['support']['locationIcon'] ?? '' }}" class="h-5 w-5 brightness-0 invert" aria-hidden="true" alt=""><span>{{ $content['support']['location'] ?? '' }}</span></p><p class="mb-2 flex items-center gap-3"><img src="{{ $content['support']['phoneIcon'] ?? '' }}" class="h-5 w-5 brightness-0 invert" aria-hidden="true" alt=""><a href="tel:{{ $content['support']['phone'] ?? '' }}">{{ $content['support']['phone'] ?? '' }}</a></p><p class="flex items-center gap-3"><img src="{{ $content['support']['emailIcon'] ?? '' }}" class="h-5 w-5 brightness-0 invert" aria-hidden="true" alt=""><a href="mailto:{{ $content['support']['email'] ?? '' }}">{{ $content['support']['email'] ?? '' }}</a></p></aside></div></div>@endif
        @endforeach</div></section>
    @endif
@endsection
